baseURL = "https://blog.greatcatlab.net"
languageCode = "en-us"
title = "A blog about my home labbing"

#select desired theme
theme = "tale"

#copyright notice
copyright = "&copy; Copyright Aaron Langley"

sectionPagesMenu = "main"
