baseURL = "https://blog.greatcatlab.net"
languageCode = "en-us"
languageName = "English"
title = "A blog about my home labbing"

#tell the robots what to do
enableRobotsTXT = true

#select desired theme
theme = "tale"

#copyright notice
copyright = "&copy; Copyright Aaron Langley"

[[menu.main]]
	name   = "Home" #label in menu bar
	weight = 10 #Should always be most to the left
	url    = "/"

[[menu.main]]
	name   = "Posts" #label in menu bar
        weight = 20 #Should always be just to right of "Home"
        url    = "/posts/"

