baseURL = "https://blog.greatcatlab.net"
languageCode = "en-us"
title = "A blog about my home labbing"

#copyright notice
copyright = "&copy; Copyright Aaron Langley"

[params]
# Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "alangley345"
    github  = "alangley345"
    linkedin = "alangley345"
    
    # Google Analytics API key.
    ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    mixpanel_api_key = "Your Mixpanel API key"
    author = "Your Name"
    avatar = "/path/to/avatar"
    contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "greatcatlab"
    themecolor = "#00234d" # Defines the tab color in Chrome for Android.
