baseURL = "https://blog.greatcatlab.net"
languageCode = "en-us"
languageName = "English"
title = "A blog about my homelab"

#tell the robots what to do
enableRobotsTXT = true

#select desired theme
theme = "tale"

#copyright notice
copyright = "&copy"

#specify author
AuthorName = "Aaron Langley"

sectionPagesMenu = "main"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
    identifier = "about"

[Permalinks]
    posts = "/posts/:filename/"