baseURL = "https://blog.greatcatlab.net"
languageCode = "en-us"
languageName = "English"
title = "A blog about my homelab"

#tell the robots what to do
enableRobotsTXT = true

#select desired theme
theme = "tale"

#copyright notice
copyright = "&copy"

#specify author
AuthorName = "Aaron Langley"

#google analytics
googleAnalytics = "UA-177082760-1"

#Set static directory
staticDir = "https://blog.greatcatlab.net/static/"

[[menu.main]]
    name = "Posts"
    weight = 10
    url = "/posts/"
    identifier = "posts"

[[menu.main]]
    name = "About"
    weight = 100
    url = "/about/"
    identifier = "about"


[Permalinks]
    posts = "/posts/:filename/"
