baseURL = "https://blog.greatcatlab.net"
languageCode = "en-us"
languageName = "English"
title = "A blog about my homelab"

#tell the robots what to do
enableRobotsTXT = true

#select desired theme
theme = "tale"

#copyright notice
copyright = "&copy"

#specify author
AuthorName = "Aaron Langley"

sectionPagesMenu = "main"

[Permalinks]
    posts = "/posts/:filename/"